name: arbolitos
description: "Aplicación para crear árboles conmemorativos virtuales."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  google_sign_in: ^6.2.1
  
  # UI/UX
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  
  # Utils
  uuid: ^4.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  equatable: ^2.0.5
  geolocator: ^9.0.2 
  qr_flutter: ^4.1.0
  model_viewer_plus: ^1.7.0
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  package_info_plus: ^5.0.1 # <-- AÑADIDO
  
  # ARCore and ARKit for AR functionality
  ar_flutter_plugin: ^0.7.3
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700